### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**
Previous try in https://github.com/flathub/org.kde.krdc/pull/54

### CODE REVIEW

**Comment by DamienGombaultRecia** [comment]
Hi.

I have installed the build, it runs with version 24.02.0 with KDE 6.0, Qt 6.6, Wayland.

I tried a local VNC connection, could not connect : 

`2024.03.15, 12:13:18.861, 330, krdc, KRDC, debug, unknown:0, unknown - input url  "localhost:5901"
2024.03.15, 12:13:18.861, 330, krdc, KRDC, debug, unknown:0, unknown - Found plugin to handle url ( "vnc://localhost:5901" ):  VncView
2024.03.15, 12:13:18.861, 330, krdc, KRDC, debug, unknown:0, unknown - Show config dialog again
2024.03.15, 12:13:20.857, 330, krdc, KRDC, debug, unknown:0, unknown - HostPreferences config dialog accepted
2024.03.15, 12:13:20.857, 330, krdc, KRDC, debug, unknown:0, unknown - -1
2024.03.15, 12:13:20.857, 330, krdc, KRDC, debug, unknown:0, unknown - -1
2024.03.15, 12:13:20.858, 330, krdc, KRDC, debug, unknown:0, unknown - 1651 1060
2024.03.15, 12:13:20.858, 330, krdc, KRDC, debug, unknown:0, unknown - 0
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - 0
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - 0
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - 0
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - RemoteView::Disconnected
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - RemoteView::Disconnecting
2024.03.15, 12:13:20.859, 330, krdc, KRDC, debug, unknown:0, unknown - RemoteView::Connecting
`

The same server works OK with vncviewer.

I tried a RDP session, could not connect :
`[12:15:04:246] [359:359] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connexion ré-initialisée par le correspondant
[12:15:04:246] [359:359] [ERROR][com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[12:15:04:643] [359:359] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connexion ré-initialisée par le correspondant
[12:15:04:643] [359:359] [ERROR][com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[12:15:04:643] [359:359] [ERROR][com.freerdp.core] - freerdp_post_connect failed
2024.03.15, 12:15:04.637, 359, krdc, KRDC, debug, unknown:0, unknown - RemoteView::Disconnected
2024.03.15, 12:15:04.637, 359, krdc, KRDC, warning, unknown:0, unknown - Unable to connect
2024.03.15, 12:15:04.637, 359, krdc, KRDC, warning, unknown:0, unknown - ERRCONNECT_CONNECT_TRANSPORT_FAILED The connection transport layer failed.
`

I don't know if this is a an packaging or app problem.
VNC and RDP works with the current stable release on Flathub.

**Comment by travier** [comment]
Ah indeed, looks like krdc only supports FreeRDP 2.10.x

**Comment by travier** [comment]
@DamienGombaultRecia Can you give this build a try? Thanks

**Comment by travier** [comment]
OK, I've also confirmed that VNC & RDP work so I'll merge this one. Thanks!

**Comment by DamienGombaultRecia** [comment]
Hi. Thanks for the build.
I can connect to VNC and RDP too !

**Pull request merged**
